name: Make Modern.TiddlyDev Template

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear
        run: |
          rm -rf .github/workflows/make-template.yml src/doc
          mkdir tmpupload
          cp -r !(tmpupload|.git) tmpupload/

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: template
          FOLDER: tmpupload
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
