name: Make Modern.TiddlyDev Template

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear
        run: |
          rm -rf .github/workflows/make-template.yml src/doc
          mkdir /temp/moderntiddlydev
          cp -r * /temp/moderntiddlydev/
          mkdir upload
          cp -r /temp/moderntiddlydev/* upload/
          mv upload/.git .git

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: template
          FOLDER: upload
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
